ific_heroku/apps/website/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from apps.website.views import *

urlpatterns = patterns('',

    # -*- Top Menu -*-

    # Sobre
    url(r'^$', SobreListView.as_view(), name='sobre'),

    # Missão
    url(r'^missao/$', MissaoTemplateView.as_view(), name='missao'),

    # Projetos
    url(r'^projetos/$', ProjetosTemplateView.as_view(), name='projetos'),

    # Transplante
    url(r'^transplante/diagnostico/$', TransplateDiagnosticoTemplateView.as_view(), name='transplante-diagnostico'),
    url(r'^transplante/cirurgia/$', TransplateCirurgiaTemplateView.as_view(), name='transplante-cirurgia'),
    url(r'^transplante/pos-operatorio/$', TransplantePosOperatorioTemplateView.as_view(), name='transplante-pos-operatorio'),
    url(r'^transplante/historias-de-vida/$', TransplanteHistoriasVidaTemplateView.as_view(), name='transplante-historias-de-vida'),

    # Prevenção
    url(r'^prevencao/doencas-hepaticas/$', PrevencaoDoencasHepaticasTemplateView.as_view(), name='prevencao-doencas-hepaticas'),
    url(r'^prevencao/alcoolismo/$', PrevencaoAlcoolismoTemplateView.as_view(), name='prevencao-alcoolismo'),
    url(r'^prevencao/poluentes-ambientais/$', PrevencaoPoluentesAmbientaisTemplateView.as_view(), name='prevencao-poluentes-ambientais'),
    url(r'^prevencao/alimentacao-e-sedentarismo/$', PrevencaoAlimentacaoSedentarismoTemplateView.as_view(), name='prevencao-alimentacao-e-sedentarismo'),
    url(r'^prevencao/medicamentos/$', PrevencaoMedicamentosTemplateView.as_view(), name='prevencao-medicamentos'),

    # -*- Side bar -*-

    # Como apoiar o IFIC
    url(r'^como-apoiar/$', ComoApoiarTemplateView.as_view(), name='como-apoiar'),

    # Seja um doador
    url(r'^seja-um-doador/$', SejaDoadorTemplateView.as_view(), name='seja-um-doador'),

    # Galeria
    url(r'^galeria/$', GaleriaListView.as_view(), name='galeria'),

    # Equipe
    url(r'^equipe/$', EquipeListView.as_view(), name='equipe'),

    # Notícias
    url(r'^noticias/$', NoticiaListView.as_view(), name='noticias'),
    url(r'^noticia/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', NoticiaDateDetailView.as_view(), name="noticia"),

    # Fale conosco
    url(r'^fale-conosco/$', ContatoView.as_view(), name='fale-conosco'),

    # Publicações científicas
    url(r'^publicacao-cientifica/$', PublicacaoCientificaListView.as_view(), name='publicacao-cientifica'),
)

ific_heroku/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url
# static imports
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# See: https://docs.djangoproject.com/en/dev/ref/contrib/admin/#hooking-adminsite-instances-into-your-urlconf
admin.autodiscover()


# See: https://docs.djangoproject.com/en/dev/topics/http/urls/
urlpatterns = patterns('',
    # Admin panel and documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('apps.website.urls', namespace='core')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

ific_heroku/apps/website/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify

class SalaImprensaDestaqueManager(models.Manager):
    def get_query_set(self):
        return super(SalaImprensaDestaqueManager, self).get_query_set().filter(destaque=True)

# Create your models here.
class SalaImprensa(models.Model):
    titulo = models.CharField(u'Título', max_length=120)
    slug = models.SlugField(max_length=120, null=True, blank=True)
    data_pub = models.DateTimeField(u'Data de publicação', auto_now_add=True)
    subtitulo = models.CharField(u'Subtítulo', max_length=120, null=True, blank=True)
    video = models.TextField(u'Vídeo', null=True, blank=True)
    texto = models.TextField('Texto', null=True, blank=True)
    link = models.CharField(u'Link', max_length=120, null=True, blank=True)
    foto = models.ImageField('Foto', upload_to='images/sala_imprensa', null=True, blank=True)
    destaque = models.BooleanField(default=False)

    # Manager
    objects = models.Manager()
    destaques = SalaImprensaDestaqueManager()

    class Meta:
        db_table = 'website_salaimprensa'
        verbose_name = u'Sala de imprensa'
        verbose_name_plural = u'Salas de imprensa'
        ordering = ['-data_pub']

    @models.permalink
    def get_absolute_url(self):
        return ('core:noticia', None, {
                'year': str(self.data_pub.year),
                'month': str(self.data_pub.month).zfill(2),
                'day': str(self.data_pub.day).zfill(2),
                'slug': str(self.slug),
            }
        )

    def __unicode__(self):
        return self.titulo


@receiver(pre_save, sender=SalaImprensa)
def save_slug_sala_imprensa(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = slugify(sender.titulo)


class Equipe(models.Model):
    ordem = models.PositiveSmallIntegerField(default=0)
    nome = models.CharField('Nome', max_length=120)
    resumo = models.TextField(u'Resumo do currículo')
    email = models.EmailField('Email', null=True, blank=True)
    site = models.URLField('Site', verify_exists=False, null=True, blank=True)
    foto = models.ImageField('Foto do colaborador', upload_to='images/equipe', null=True, blank=True)
    data_pub = models.DateTimeField(u'Data de publicação', auto_now_add=True)
    
    class Meta:
        db_table = 'website_equipe'
        verbose_name = u'Membro da equipe'
        verbose_name_plural = u'Membros da equipe'
        ordering = ['ordem']
    
    def __unicode__(self):
        return self.nome


class Galeria(models.Model):
    ordem = models.AutoField(u'Ordenação das fotos', primary_key=True)
    foto = models.ImageField('Foto', upload_to='images/gallery', null=True, blank=True)
    thumb = models.ImageField('Thumb', upload_to='images/gallery', null=True, blank=True)
    texto = models.TextField(u'Subtítulo da foto', null=True, blank=True)
    data_pub = models.DateTimeField(u'Data de publicação', auto_now_add=True)

    class Meta:
        db_table = 'website_galeria'
        verbose_name = u'Galeria'
        verbose_name_plural = u'Galerias'
        ordering = ['ordem']

    def __unicode__(self):
        return '%d - %s' % (self.ordem, self.texto)

class PublicacaoCientifica(models.Model):
    ordem = models.AutoField(u'Ordenação das fotos', primary_key=True)
    titulo = models.CharField(u'Título', max_length=120, null=True, blank=True)
    descricao = models.TextField(u'Descrição', null=True, blank=True)
    arquivo = models.FileField(upload_to='docs/publicacoes')

    class Meta:
        db_table = 'website_publicacao_cientifica'
        verbose_name = u'Publicação científica'
        verbose_name_plural = u'Publicações científicas'
        ordering = ['ordem', 'titulo']

    def __unicode__(self):
        if self.titulo:
            return self.titulo
        else:
            return self.ordem

ific_heroku/apps/website/forms.py
from django import forms
from django.core.mail import send_mail

class FaleConoscoForm(forms.Form):
    subject = forms.CharField(
        label=u'Assunto',
        widget=forms.TextInput(attrs={'class': 'input-xlarge'})
    )
    from_email = forms.EmailField(
        label=u'Email',
        widget=forms.TextInput(attrs={'class': 'input-xlarge'})
    )
    message = forms.CharField(
        label=u'Mensagem',
        widget=forms.Textarea(attrs={'class': 'input-xlarge', 'rows': 5})
    )

    def enviar_email(self):
        return send_mail(
            self.cleaned_data['subject'],
            self.cleaned_data['message'],
            self.cleaned_data['from_email'],
            ['macndesign@gmail.com'],
            fail_silently = False
        )

ific_heroku/apps/website/views.py
# -*- coding: utf-8 -*-
# Create your views here.
from django.core.mail import send_mail
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from apps.website.forms import FaleConoscoForm
from apps.website.models import Galeria, Equipe, PublicacaoCientifica, SalaImprensa
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.views.generic.dates import DateDetailView
from django.views.generic.edit import FormView
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages

class SobreListView(ListView):
    queryset = SalaImprensa.destaques.all()
    template_name = 'website/sobre-o-ific.html'
    context_object_name = 'destaques'


class MissaoTemplateView(TemplateView):
    template_name = 'website/missao.html'


class ProjetosTemplateView(TemplateView):
    template_name = 'website/projetos.html'


class TransplateDiagnosticoTemplateView(TemplateView):
    template_name = 'website/transplante-diagnostico.html'


class TransplateCirurgiaTemplateView(TemplateView):
    template_name = 'website/transplante-cirurgia.html'


class TransplantePosOperatorioTemplateView(TemplateView):
    template_name = 'website/transplante-pos-operatorio.html'


class TransplanteHistoriasVidaTemplateView(TemplateView):
    template_name = 'website/transplante-historias-de-vida.html'


class PrevencaoDoencasHepaticasTemplateView(TemplateView):
    template_name = 'website/prevencao-doencas-hepaticas.html'


class PrevencaoAlcoolismoTemplateView(TemplateView):
    template_name = 'website/prevencao-alcoolismo.html'


class PrevencaoPoluentesAmbientaisTemplateView(TemplateView):
    template_name = 'website/prevencao-poluentes-ambientais.html'


class PrevencaoAlimentacaoSedentarismoTemplateView(TemplateView):
    template_name = 'website/prevencao-alimentacao-e-sedentarismo.html'


class PrevencaoMedicamentosTemplateView(TemplateView):
    template_name = 'website/prevencao-medicamentos.html'


class ComoApoiarTemplateView(TemplateView):
    template_name = 'website/como-apoiar.html'


class SejaDoadorTemplateView(TemplateView):
    template_name = 'website/seja-um-doador.html'


class GaleriaListView(ListView):
    model = Galeria
    template_name = 'website/galeria.html'
    paginate_by = 9


class EquipeListView(ListView):
    model = Equipe
    template_name = 'website/equipe.html'
    paginate_by = 9


class PublicacaoCientificaListView(ListView):
    model = PublicacaoCientifica
    template_name = 'website/publicacao-cientifica.html'
    paginate_by = 9


class NoticiaListView(ListView):
    model = SalaImprensa
    template_name = 'website/noticias.html'
    paginate_by = 9


class NoticiaDateDetailView(DateDetailView):
    model = SalaImprensa
    template_name = 'website/noticia.html'
    context_object_name = 'noticia'
    date_field = 'data_pub'
    year_format = '%Y'
    month_format = '%m'
    day_format = '%d'
    slug_field = 'slug'


class ContatoView(FormView):
    template_name = 'website/contato.html'
    form_class = FaleConoscoForm

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, u'Email enviado com sucesso.')
        return reverse_lazy('core:fale-conosco')

    def form_valid(self, form):
        form.enviar_email()
        return super(ContatoView, self).form_valid(form)

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, u'Formulário inválido.')
        return super(ContatoView, self).form_invalid(form)

ific_heroku/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>IFIC - Instituto do Fígado do Ceará</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/style-responsive.css" rel="stylesheet">
    {% block extra_css %}{% endblock %}

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="{{ STATIC_URL }}ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{ STATIC_URL }}ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ STATIC_URL }}ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ STATIC_URL }}ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="{{ STATIC_URL }}ico/apple-touch-icon-57-precomposed.png">
    {% block extra_head %}{% endblock %}
</head>

<body>

{% include "website/navbar-fixed-top.html" %}

<div class="container">

    <div class="row">
	
		<div class="span3">
            {% include "website/side-bar.html" %}
        </div>
        
        <div class="span9">
        {% block breadcrumb %}{% endblock %}
        {% block content %}{% endblock %}
        </div>
		
    </div>

    <footer class="footer">
        <p class="pull-right"><a href="#">Ir para o topo</a></p>
        <p>&copy; <a href="http://ific.org.br" target="_blank">IFIC - Instituto do Fígado do Ceará</a> - Todos os direitos reservados.</p>
    </footer>

</div>
<!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ STATIC_URL }}js/jquery.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-transition.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-alert.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-modal.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-dropdown.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-scrollspy.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-tab.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-tooltip.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-popover.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-button.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-collapse.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-carousel.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-typeahead.js"></script>
<script>$('#myCarousel').carousel()</script>
{% block extra_js %}{% endblock %}
</body>
</html>

ific_heroku/templates/website/contato.html
{% extends "website/base.html" %}

{% block extra_css %}
    <style>
    ul.messages {
        margin-left: 0;
    }
    ul.messages > li {
        list-style: none;
        padding: 8px 10px;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
    }
    .help-block ul.errorlist li {
        list-style: none;
    }
    .help-block ul.errorlist {
        margin: 0;
    }
    </style>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" xmlns="http://www.w3.org/1999/html">
        $(function(){
            $(".side-bar").find(".fale-conosco").addClass("active");
            $("input[type=text]:first").focus();
            $(".error").find("input[type=text]:first").focus();
            $(".error").find("textarea").focus();
        });
    </script>
{% endblock %}

<!-- Breadcrumber -->
{% block breadcrumb %}
<ul class="breadcrumb">
    <li><a href="{% url core:sobre %}">Home</a> <span class="divider">/</span></li>
    <li class="active">Fale conosco</li>
</ul>
{% endblock %}

<!-- Título -->
{% block content %}

    <div class="page-header">
        <h1>Fale conosco</h1>
    </div>

    <div class="row">
        <div class="span5 pull-left">

            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <form class="form-horizontal" action="{% url core:fale-conosco %}" method="post">{% csrf_token %}
                {{ form.non_field_errors }}
                <fieldset>
                    <div class="control-group{% if form.subject.errors %} error{% endif %}">
                        <label class="control-label" for="id_subject">{{ form.subject.label }}</label>
                        <div class="controls">
                            {{ form.subject }}
                            {% if form.subject.errors %}
                                <span class="help-block">{{ form.subject.errors }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="control-group{% if form.from_email.errors %} error{% endif %}">
                        <label class="control-label" for="id_from_email">{{ form.from_email.label }}</label>
                        <div class="controls">
                            {{ form.from_email }}
                            {% if form.from_email.errors %}
                                <span class="help-block">{{ form.from_email.errors }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="control-group{% if form.message.errors %} error{% endif %}">
                        <label class="control-label" for="id_message">{{ form.message.label }}</label>
                        <div class="controls">
                            {{ form.message }}
                            {% if form.message.errors %}
                                <span class="help-block">{{ form.message.errors }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </fieldset>
            </form>
        </div>
        <ul class="thumbnails pull-right">
            <li class="span4">
                <div class="thumbnail">
                    <img src="http://placehold.it/360x268" alt="">
                </div>
            </li>
        </ul>
    </div>

{% endblock %}

ific_heroku/templates/website/equipe.html
{% extends "website/base.html" %}

{% block extra_js %}
    <script type="text/javascript" xmlns="http://www.w3.org/1999/html">
        $(function(){
            $(".side-bar").find(".equipe").addClass("active");
        });
    </script>
{% endblock %}

<!-- Breadcrumber -->
{% block breadcrumb %}
    <ul class="breadcrumb">
        <li><a href="{% url core:sobre %}">Home</a> <span class="divider">/</span></li>
        <li class="active">Equipe</li>
        <li class="pull-right">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">
                    <i class="icon-arrow-left"></i>
                    Anterior
                </a> -
            {% endif %}
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
            {% if page_obj.has_next %}
                - <a href="?page={{ page_obj.next_page_number }}">
                Próxima
                <i class="icon-arrow-right"></i>
            </a>
            {% endif %}
        </li>
    </ul>
{% endblock %}

<!-- Título -->
{% block content %}

    <div class="page-header">
        <h1>Equipe</h1>
    </div>

    {% if page_obj.object_list %}
        {% for item in page_obj.object_list %}
            <div class="row">
                <div class="span2">
                    <div class="thumbnail" style="background: #f7f7f7">
                        <img src="{{ item.foto.url }}" alt="{{ item.nome }}" title="{{ item.nome }}" width="170" height="170" />
                    </div>
                </div>

                <h3 class="span7">{{ item.nome }}</h3>
                <p class="span7">{{ item.resumo|linebreaksbr }}</p>
                <p class="span7">{% if item.email %}Email: <a href="mailto:{{ item.email }}" target="_blank">{{ item.email }}</a><br />{% endif %}
                {% if item.site %}Site: <a href="{{ item.site }}" target="_blank">{{ item.site }}</a>{% endif %}</p>
            </div><br />
        {% endfor %}
    {% endif %}

{% endblock %}

ific_heroku/templates/website/left-pubs.html
<ul class="thumbnails">
    <li class="span3">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x80" alt="" height="80" width="260">
        </a>
    </li>
    <li class="span3">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x80" alt="" height="80" width="260">
        </a>
    </li>
    <li class="span3">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x80" alt="" height="80" width="260">
        </a>
    </li>
    <li class="span3">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x80" alt="" height="80" width="260">
        </a>
    </li>
</ul>

ific_heroku/templates/website/prevencao-alimentacao-e-sedentarismo.html
{% extends "website/base.html" %}

{% block extra_js %}
    <script type="text/javascript" xmlns="http://www.w3.org/1999/html">
        $(function(){
            $(".prevencao").addClass("active");
            $(".prevencao").find(".alimentacao-e-sedentarismo").addClass("active");
        });
    </script>
{% endblock %}

<!-- Breadcrumber -->
{% block breadcrumb %}
<ul class="breadcrumb">
    <li><a href="{% url core:sobre %}">Home</a> <span class="divider">/</span></li>
    <li>Prevenção <span class="divider">/</span></li>
    <li class="active">Alimentação e Sedentarismo</li>
</ul>
{% endblock %}

<!-- Título -->
{% block content %}

    <div class="page-header">
        <h1>Prevenção</h1>
    </div>

    <div class="row">
        <div class="span5 pull-left">
            <h2>Alimentação e Sedentarismo</h2><br />
            <p>A obesidade, o diabetes, o aumento de colesterol ou triglicerídeos no sangue e a vida sedentária podem levar ao acúmulo de gordura no fígado – esteatose hepática ou “fígado gorduroso” – que pode causar problemas futuros no funcionamento do seu fígado se não tratada adequadamente. Então, procure manter uma alimentação saudável e praticar exercícios físicos regularmente.</p>
        </div>
        <ul class="thumbnails pull-right">
            <li class="span4">
                <div class="thumbnail">
                    <img src="http://placehold.it/360x268" alt="">
                </div>
            </li>
        </ul>
    </div>

{% endblock %}

ific_heroku/templates/website/prevencao-medicamentos.html
{% extends "website/base.html" %}

{% block extra_js %}
    <script type="text/javascript" xmlns="http://www.w3.org/1999/html">
        $(function(){
            $(".prevencao").addClass("active");
            $(".prevencao").find(".medicamentos").addClass("active");
        });
    </script>
{% endblock %}

<!-- Breadcrumber -->
{% block breadcrumb %}
<ul class="breadcrumb">
    <li><a href="{% url core:sobre %}">Home</a> <span class="divider">/</span></li>
    <li>Prevenção <span class="divider">/</span></li>
    <li class="active">Medicamentos</li>
</ul>
{% endblock %}

<!-- Título -->
{% block content %}

    <div class="page-header">
        <h1>Prevenção</h1>
    </div>

    <div class="row">
        <div class="span5 pull-left">
            <h2>Medicamentos</h2><br />
            <p>Medicamentos, inclusive os aparentemente inofensivos, como o paracetamol, nunca devem ser tomados com bebidas alcoólicas. Muitas drogas e medicamentos prescritos ou isentos se prescrição contêm químicos que podem ser potencialmente prejudiciais às células do seu fígado, principalmente se ingeridas com álcool.</p>
            <p>Vários remédios de uso clínico podem causar hepatite em indivíduos suscetíveis. Não se pode prever quem terá hepatite por determinada droga, porém, indivíduos que já têm outras formas de doença do fígado correm maior risco. Alguns medicamentos relacionados com hepatite são: paracetamol, antibióticos e antifúngicos (eritromicina, tetraciclina, sulfas, cetoconazol e nitrofurantoína), anabolizantes (hormônios usados para melhorar o desempenho físico), drogas antipsicóticas e calmantes, drogas antiarrítimicas (amiodarona), anti-hipertensivos (metildopa), antituberculosos. Anticoncepcionais orais também são ocasionalmente mencionados.</p>
            <p>Cuidado com o uso de fitoterápicos, ervas, chás e suplementos dietéticos. O uso excessivo dessas substâncias também pode causar hepatite. Procure sempre seu médico e esclareça suas dúvidas! Cuidado com o que você toma!</p>
        </div>
        <ul class="thumbnails pull-right">
            <li class="span4">
                <div class="thumbnail">
                    <img src="http://placehold.it/360x268" alt="">
                </div>
            </li>
        </ul>
    </div>

{% endblock %}

ific_heroku/templates/website/side-bar.html
<a href="/"><img src="{{ STATIC_URL }}img/logo.png" alt="Pulse" title="Pulse"></a>
<div class="well side-bar" style="padding: 8px 0; margin-top: 18px;">
    {% include "website/left-menu.html" %}
</div>
{% include "website/left-pubs.html" %}

ific_heroku/templates/website/top-menu.html
{% load url from future %}
<ul class="nav">
    <li class="home"><a href="{% url "core:sobre" %}">Home</a></li>
    <li class="missao"><a href="{% url "core:missao" %}">Missão</a></li>
    <li class="projetos"><a href="{% url "core:projetos" %}">Projetos</a></li>
    <li class="dropdown transplante">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Transplante <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li class="diagnostico"><a href="{% url "core:transplante-diagnostico" %}">Diagnóstico</a></li>
            <li class="cirurgia"><a href="{% url "core:transplante-cirurgia" %}">Cirurgia</a></li>
            <li class="pos-operatorio"><a href="{% url "core:transplante-pos-operatorio" %}">Pós-operatório</a></li>
            <li class="historias-de-vida"><a href="{% url "core:transplante-historias-de-vida" %}">Histórias de vida</a></li>
        </ul>
    </li>
    <li class="dropdown prevencao">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Prevenção <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li class="doencas-hepaticas"><a href="{% url "core:prevencao-doencas-hepaticas" %}">Doenças Hepáticas</a></li>
            <li class="alcoolismo"><a href="{% url "core:prevencao-alcoolismo" %}">Alcoolismo</a></li>
            <li class="poluentes-ambientais"><a href="{% url "core:prevencao-poluentes-ambientais" %}">Poluentes Ambientais</a></li>
            <li class="alimentacao-e-sedentarismo"><a href="{% url "core:prevencao-alimentacao-e-sedentarismo" %}">Alimentação e Sedentarismo</a></li>
            <li class="medicamentos"><a href="{% url "core:prevencao-medicamentos" %}">Medicamentos</a></li>
        </ul>
    </li>
</ul>

ific_heroku/templates/website/top-search.html
<form class="navbar-search pull-right" action="">
    <input type="text" class="search-query span2" placeholder="Search">
</form>